### ISSUE TITLE
Custom environment in config

### ISSUE THREAD

**Issue by johnnyhoichuen** [Tviskaron/pogema-baselines#12]
In the config files, e.g.
```
algo:
  grid_search: [ QMIX, VDN, IQL, ]
settings:
  t_max: 8000000
logging:
  use_wandb: True
  project_name: "Pogema-32x32-PyMARL"
env_args:
  grid_config:
    map_name:
      grid_search: [Easy32x32, Normal32x32, Hard32x32, ExtraHard32x32]
```

the environments are predefined by pogema library. Is it possible to pass a custom environment (GridConfig) here with different map size, FOV, obstacle density, etc?
